# Generated by Django 4.0.4 on 2022-06-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topics',
            new_name='topic',
        ),
    ]
